[project]
name = "easyfind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.0"
dependencies = [
    "setuptools>=80.9.0",
    "twine>=6.2.0",
    "wheel>=0.45.1",
]
